import { Pathnames } from 'next-intl/navigation'

export const locales = ['en', 'ch', 'jp', 'ko', 'es', 'fr', 'de', 'it', 'pt', 'ru', 'ar', 'hi'] as const

export const pathnames = {
    '/': '/',
    '/pathnames': {
        en: '/',
        ch: '/ch',
        jp: '/jp',
        ko: '/ko',
        es: '/es',
        fr: '/fr',
        de: '/de',
        it: '/it',
        pt: '/pt',
        ru: '/ru',
        ar: '/ar',
        hi: '/hi',
    },
    '/binary-to-decimal-conversion': {
        en: '/binary-to-decimal-conversion',
        ch: '/binary-to-decimal-conversion',
        jp: '/binary-to-decimal-conversion',
        ko: '/binary-to-decimal-conversion',
        es: '/binary-to-decimal-conversion',
        fr: '/binary-to-decimal-conversion',
        de: '/binary-to-decimal-conversion',
        it: '/binary-to-decimal-conversion',
        pt: '/binary-to-decimal-conversion',
        ru: '/binary-to-decimal-conversion',
        ar: '/binary-to-decimal-conversion',
        hi: '/binary-to-decimal-conversion',
    },
    '/binary-to-hexadecimal-conversion': {
        en: '/binary-to-hexadecimal-conversion',
        ch: '/binary-to-hexadecimal-conversion',
        jp: '/binary-to-hexadecimal-conversion',
        ko: '/binary-to-hexadecimal-conversion',
        es: '/binary-to-hexadecimal-conversion',
        fr: '/binary-to-hexadecimal-conversion',
        de: '/binary-to-hexadecimal-conversion',
        it: '/binary-to-hexadecimal-conversion',
        pt: '/binary-to-hexadecimal-conversion',
        ru: '/binary-to-hexadecimal-conversion',
        ar: '/binary-to-hexadecimal-conversion',
        hi: '/binary-to-hexadecimal-conversion',
    },
    '/binary-to-octal-conversion': {
        en: '/binary-to-octal-conversion',
        ch: '/binary-to-octal-conversion',
        jp: '/binary-to-octal-conversion',
        ko: '/binary-to-octal-conversion',
        es: '/binary-to-octal-conversion',
        fr: '/binary-to-octal-conversion',
        de: '/binary-to-octal-conversion',
        it: '/binary-to-octal-conversion',
        pt: '/binary-to-octal-conversion',
        ru: '/binary-to-octal-conversion',
        ar: '/binary-to-octal-conversion',
        hi: '/binary-to-octal-conversion',
    },
    '/binary-to-text-conversion': {
        en: '/binary-to-text-conversion',
        ch: '/binary-to-text-conversion',
        jp: '/binary-to-text-conversion',
        ko: '/binary-to-text-conversion',
        es: '/binary-to-text-conversion',
        fr: '/binary-to-text-conversion',
        de: '/binary-to-text-conversion',
        it: '/binary-to-text-conversion',
        pt: '/binary-to-text-conversion',
        ru: '/binary-to-text-conversion',
        ar: '/binary-to-text-conversion',
        hi: '/binary-to-text-conversion',
    },
    '/decimal-to-binary-conversion': {
        en: '/decimal-to-binary-conversion',
        ch: '/decimal-to-binary-conversion',
        jp: '/decimal-to-binary-conversion',
        ko: '/decimal-to-binary-conversion',
        es: '/decimal-to-binary-conversion',
        fr: '/decimal-to-binary-conversion',
        de: '/decimal-to-binary-conversion',
        it: '/decimal-to-binary-conversion',
        pt: '/decimal-to-binary-conversion',
        ru: '/decimal-to-binary-conversion',
        ar: '/decimal-to-binary-conversion',
        hi: '/decimal-to-binary-conversion',
    },
    '/decimal-to-hexadecimal-conversion': {
        en: '/decimal-to-hexadecimal-conversion',
        ch: '/decimal-to-hexadecimal-conversion',
        jp: '/decimal-to-hexadecimal-conversion',
        ko: '/decimal-to-hexadecimal-conversion',
        es: '/decimal-to-hexadecimal-conversion',
        fr: '/decimal-to-hexadecimal-conversion',
        de: '/decimal-to-hexadecimal-conversion',
        it: '/decimal-to-hexadecimal-conversion',
        pt: '/decimal-to-hexadecimal-conversion',
        ru: '/decimal-to-hexadecimal-conversion',
        ar: '/decimal-to-hexadecimal-conversion',
        hi: '/decimal-to-hexadecimal-conversion',
    },
    '/decimal-to-octal-conversion': {
        en: '/decimal-to-octal-conversion',
        ch: '/decimal-to-octal-conversion',
        jp: '/decimal-to-octal-conversion',
        ko: '/decimal-to-octal-conversion',
        es: '/decimal-to-octal-conversion',
        fr: '/decimal-to-octal-conversion',
        de: '/decimal-to-octal-conversion',
        it: '/decimal-to-octal-conversion',
        pt: '/decimal-to-octal-conversion',
        ru: '/decimal-to-octal-conversion',
        ar: '/decimal-to-octal-conversion',
        hi: '/decimal-to-octal-conversion',
    },
    '/decimal-to-text-conversion': {
        en: '/decimal-to-text-conversion',
        ch: '/decimal-to-text-conversion',
        jp: '/decimal-to-text-conversion',
        ko: '/decimal-to-text-conversion',
        es: '/decimal-to-text-conversion',
        fr: '/decimal-to-text-conversion',
        de: '/decimal-to-text-conversion',
        it: '/decimal-to-text-conversion',
        pt: '/decimal-to-text-conversion',
        ru: '/decimal-to-text-conversion',
        ar: '/decimal-to-text-conversion',
        hi: '/decimal-to-text-conversion',
    },
    '/hexadecimal-to-binary-conversion': {
        en: '/hexadecimal-to-binary-conversion',
        ch: '/hexadecimal-to-binary-conversion',
        jp: '/hexadecimal-to-binary-conversion',
        ko: '/hexadecimal-to-binary-conversion',
        es: '/hexadecimal-to-binary-conversion',
        fr: '/hexadecimal-to-binary-conversion',
        de: '/hexadecimal-to-binary-conversion',
        it: '/hexadecimal-to-binary-conversion',
        pt: '/hexadecimal-to-binary-conversion',
        ru: '/hexadecimal-to-binary-conversion',
        ar: '/hexadecimal-to-binary-conversion',
        hi: '/hexadecimal-to-binary-conversion',
    },
    '/hexadecimal-to-decimal-conversion': {
        en: '/hexadecimal-to-decimal-conversion',
        ch: '/hexadecimal-to-decimal-conversion',
        jp: '/hexadecimal-to-decimal-conversion',
        ko: '/hexadecimal-to-decimal-conversion',
        es: '/hexadecimal-to-decimal-conversion',
        fr: '/hexadecimal-to-decimal-conversion',
        de: '/hexadecimal-to-decimal-conversion',
        it: '/hexadecimal-to-decimal-conversion',
        pt: '/hexadecimal-to-decimal-conversion',
        ru: '/hexadecimal-to-decimal-conversion',
        ar: '/hexadecimal-to-decimal-conversion',
        hi: '/hexadecimal-to-decimal-conversion',
    },
    '/hexadecimal-to-octal-conversion': {
        en: '/hexadecimal-to-octal-conversion',
        ch: '/hexadecimal-to-octal-conversion',
        jp: '/hexadecimal-to-octal-conversion',
        ko: '/hexadecimal-to-octal-conversion',
        es: '/hexadecimal-to-octal-conversion',
        fr: '/hexadecimal-to-octal-conversion',
        de: '/hexadecimal-to-octal-conversion',
        it: '/hexadecimal-to-octal-conversion',
        pt: '/hexadecimal-to-octal-conversion',
        ru: '/hexadecimal-to-octal-conversion',
        ar: '/hexadecimal-to-octal-conversion',
        hi: '/hexadecimal-to-octal-conversion',
    },
    '/hexadecimal-to-text-conversion': {
        en: '/hexadecimal-to-text-conversion',
        ch: '/hexadecimal-to-text-conversion',
        jp: '/hexadecimal-to-text-conversion',
        ko: '/hexadecimal-to-text-conversion',
        es: '/hexadecimal-to-text-conversion',
        fr: '/hexadecimal-to-text-conversion',
        de: '/hexadecimal-to-text-conversion',
        it: '/hexadecimal-to-text-conversion',
        pt: '/hexadecimal-to-text-conversion',
        ru: '/hexadecimal-to-text-conversion',
        ar: '/hexadecimal-to-text-conversion',
        hi: '/hexadecimal-to-text-conversion',
    },
    '/octal-to-binary-conversion': {
        en: '/octal-to-binary-conversion',
        ch: '/octal-to-binary-conversion',
        jp: '/octal-to-binary-conversion',
        ko: '/octal-to-binary-conversion',
        es: '/octal-to-binary-conversion',
        fr: '/octal-to-binary-conversion',
        de: '/octal-to-binary-conversion',
        it: '/octal-to-binary-conversion',
        pt: '/octal-to-binary-conversion',
        ru: '/octal-to-binary-conversion',
        ar: '/octal-to-binary-conversion',
        hi: '/octal-to-binary-conversion',
    },
    '/octal-to-decimal-conversion': {
        en: '/octal-to-decimal-conversion',
        ch: '/octal-to-decimal-conversion',
        jp: '/octal-to-decimal-conversion',
        ko: '/octal-to-decimal-conversion',
        es: '/octal-to-decimal-conversion',
        fr: '/octal-to-decimal-conversion',
        de: '/octal-to-decimal-conversion',
        it: '/octal-to-decimal-conversion',
        pt: '/octal-to-decimal-conversion',
        ru: '/octal-to-decimal-conversion',
        ar: '/octal-to-decimal-conversion',
        hi: '/octal-to-decimal-conversion',
    },
    '/octal-to-hexadecimal-conversion': {
        en: '/octal-to-hexadecimal-conversion',
        ch: '/octal-to-hexadecimal-conversion',
        jp: '/octal-to-hexadecimal-conversion',
        ko: '/octal-to-hexadecimal-conversion',
        es: '/octal-to-hexadecimal-conversion',
        fr: '/octal-to-hexadecimal-conversion',
        de: '/octal-to-hexadecimal-conversion',
        it: '/octal-to-hexadecimal-conversion',
        pt: '/octal-to-hexadecimal-conversion',
        ru: '/octal-to-hexadecimal-conversion',
        ar: '/octal-to-hexadecimal-conversion',
        hi: '/octal-to-hexadecimal-conversion',
    },
    '/octal-to-text-conversion': {
        en: '/octal-to-text-conversion',
        ch: '/octal-to-text-conversion',
        jp: '/octal-to-text-conversion',
        ko: '/octal-to-text-conversion',
        es: '/octal-to-text-conversion',
        fr: '/octal-to-text-conversion',
        de: '/octal-to-text-conversion',
        it: '/octal-to-text-conversion',
        pt: '/octal-to-text-conversion',
        ru: '/octal-to-text-conversion',
        ar: '/octal-to-text-conversion',
        hi: '/octal-to-text-conversion',
    },
    '/what-is-binary-code': {
        en: '/what-is-binary-code',
        ch: '/what-is-binary-code',
        jp: '/what-is-binary-code',
        ko: '/what-is-binary-code',
        es: '/what-is-binary-code',
        fr: '/what-is-binary-code',
        de: '/what-is-binary-code',
        it: '/what-is-binary-code',
        pt: '/what-is-binary-code',
        ru: '/what-is-binary-code',
        ar: '/what-is-binary-code',
        hi: '/what-is-binary-code',
    },
    '/what-is-hexadecimal-code': {
        en: '/what-is-hexadecimal-code',
        ch: '/what-is-hexadecimal-code',
        jp: '/what-is-hexadecimal-code',
        ko: '/what-is-hexadecimal-code',
        es: '/what-is-hexadecimal-code',
        fr: '/what-is-hexadecimal-code',
        de: '/what-is-hexadecimal-code',
        it: '/what-is-hexadecimal-code',
        pt: '/what-is-hexadecimal-code',
        ru: '/what-is-hexadecimal-code',
        ar: '/what-is-hexadecimal-code',
        hi: '/what-is-hexadecimal-code',
    },
    '/what-is-octal-code': {
        en: '/what-is-octal-code',
        ch: '/what-is-octal-code',
        jp: '/what-is-octal-code',
        ko: '/what-is-octal-code',
        es: '/what-is-octal-code',
        fr: '/what-is-octal-code',
        de: '/what-is-octal-code',
        it: '/what-is-octal-code',
        pt: '/what-is-octal-code',
        ru: '/what-is-octal-code',
        ar: '/what-is-octal-code',
        hi: '/what-is-octal-code',
    }
} satisfies Pathnames<typeof locales>

// Use the default: `always`
export const localePrefix = "as-needed"

export type AppPathnames = keyof typeof pathnames
